name: TD3
dependencies:
    - python==2.7
    - numpy==1.13.0
    - scipy
    - pandas
    - pytorch==0.4.0
    - torchvision
    - pip:
        - tqdm
        - mujoco_py==0.5.7
        - git+https://github.com/openai/gym.git@v0.7.4#egg=gym
        - opencv-python
